apiVersion: core.codius.org/v1alpha1
kind: Service
metadata:
  name: service-sample-with-secret
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
    env:
    - name: CODIUS_PUBLIC_URI
      value: https://c8s.example.com
    - name: CODIUS_SECRET
      valueFrom:
        secretKeyRef:
          key: password
  port: 80
secretData:
  nonce: abc123
  password: secret
