apiVersion: core.codius.org/v1alpha1
kind: Service
metadata:
  name: service-sample
spec:
  containers:
  - name: test
    image: androswong418/codius-test-image@sha256:0dce885c4e558a8a7612b80e3c7f5faa54520ed27836b1f892962cf855d031a2
    env:
    - name: CODIUS_PUBLIC_URI
      value: https://codius.example.com
    - name: CODIUS_SECRET
      valueFrom:
        secretKeyRef:
          key: password
    readinessProbe:
      httpGet:
        path: /
        port: 3000
      failureThreshold: 3
      periodSeconds: 1
  port: 3000
secretData:
  nonce: abc123
  password: secret
